### ISSUE TITLE
Python 3.12 Support

### ISSUE THREAD

**Issue by b3n4kh** [helpmefindaname/transformer-smaller-training-vocab#12]
With the currently pinned [sentencepiece](https://github.com/google/sentencepiece/releases) version, this project can not be run on python 3.12

https://github.com/helpmefindaname/transformer-smaller-training-vocab/blob/90a2d498559505dd3e73a35f3fa1620792f82827/pyproject.toml#L15C1

**Comment by helpmefindaname** [comment]
Hi @b3n4kh and thank you for your report.

I have updated the dependencies and the testing to ensure python 3.12 compatibility.
Version `0.4.0` now has active python 3.12 support
